/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import java.applet.AudioClip;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marcos
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dueño = new javax.swing.JMenuItem();
        mascota = new javax.swing.JMenuItem();
        especie = new javax.swing.JMenuItem();
        raza = new javax.swing.JMenuItem();
        vacuna = new javax.swing.JMenuItem();
        enfermedad = new javax.swing.JMenuItem();
        enferVacuna = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        crearCita = new javax.swing.JMenuItem();
        crearConsulta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mostrarCita = new javax.swing.JMenuItem();
        mostrarConsulta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 196, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/sleeping_old_dog.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 57, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Veterinaria Mascota Feliz");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 29, 319, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/fondo.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(639, 541));
        jLabel3.setPreferredSize(new java.awt.Dimension(639, 541));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 660, 610));

        jMenu1.setText("Mantenimiento");

        dueño.setText("Dueño");
        dueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueñoActionPerformed(evt);
            }
        });
        jMenu1.add(dueño);

        mascota.setText("Mascota");
        mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mascotaActionPerformed(evt);
            }
        });
        jMenu1.add(mascota);

        especie.setText("Especie");
        especie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieActionPerformed(evt);
            }
        });
        jMenu1.add(especie);

        raza.setText("Raza");
        raza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaActionPerformed(evt);
            }
        });
        jMenu1.add(raza);

        vacuna.setText("Vacuna");
        vacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacunaActionPerformed(evt);
            }
        });
        jMenu1.add(vacuna);

        enfermedad.setText("Enfermedad");
        enfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermedadActionPerformed(evt);
            }
        });
        jMenu1.add(enfermedad);

        enferVacuna.setText("Enfermedad Vacuna");
        enferVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enferVacunaActionPerformed(evt);
            }
        });
        jMenu1.add(enferVacuna);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");

        crearCita.setText("Crear Cita");
        crearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCitaActionPerformed(evt);
            }
        });
        jMenu2.add(crearCita);

        crearConsulta.setText("Crear Consulta");
        jMenu2.add(crearConsulta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultas");

        mostrarCita.setText("Mostrar Citas");
        jMenu3.add(mostrarCita);

        mostrarConsulta.setText("Mostrar Consultas");
        jMenu3.add(mostrarConsulta);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mascotaActionPerformed
        try {
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/multimedia/ladrido.wav"));
            sonido.play();
            this.dispose();
            FrameMantenimientoMascota mMascota = new FrameMantenimientoMascota();
            mMascota.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mascotaActionPerformed

    private void dueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueñoActionPerformed
        try {
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/multimedia/ladrido.wav"));
            sonido.play();
            this.dispose();
            FrameMantenimientoDueño mDueño = new FrameMantenimientoDueño();
            mDueño.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dueñoActionPerformed

    private void especieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieActionPerformed
        try {
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/multimedia/ladrido.wav"));
            sonido.play();
            this.dispose();
            FrameMantenimientoEspecie mEspecie = new FrameMantenimientoEspecie();
            mEspecie.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_especieActionPerformed

    private void razaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaActionPerformed
        try {
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/multimedia/ladrido.wav"));
            sonido.play();
            this.dispose();
            FrameMantenimientoRaza mRaza = new FrameMantenimientoRaza();
            mRaza.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_razaActionPerformed

    private void vacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacunaActionPerformed
        try {
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/multimedia/ladrido.wav"));
            sonido.play();
            this.dispose();
            FrameMantenimientoVacuna mVacuna = new FrameMantenimientoVacuna();
            mVacuna.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vacunaActionPerformed

    private void enfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermedadActionPerformed
        try {
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/multimedia/ladrido.wav"));
            sonido.play();
            this.dispose();
            FrameMantenimientoEnfermedad mEnfermedad = new FrameMantenimientoEnfermedad();
            mEnfermedad.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enfermedadActionPerformed

    private void crearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCitaActionPerformed
        try {
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/multimedia/ladrido.wav"));
            sonido.play();
            this.dispose();
            FrameCrearCita cita = new FrameCrearCita();
            cita.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_crearCitaActionPerformed

    private void enferVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enferVacunaActionPerformed
          try {
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/multimedia/ladrido.wav"));
            sonido.play();
            this.dispose();
            FrameMantenimientoVacunaEnfermedad e = new FrameMantenimientoVacunaEnfermedad();
            e.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enferVacunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem crearCita;
    private javax.swing.JMenuItem crearConsulta;
    private javax.swing.JMenuItem dueño;
    private javax.swing.JMenuItem enferVacuna;
    private javax.swing.JMenuItem enfermedad;
    private javax.swing.JMenuItem especie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mascota;
    private javax.swing.JMenuItem mostrarCita;
    private javax.swing.JMenuItem mostrarConsulta;
    private javax.swing.JMenuItem raza;
    private javax.swing.JMenuItem vacuna;
    // End of variables declaration//GEN-END:variables
}
