/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class FrameMantenimientoDueño extends javax.swing.JFrame {

    /**
     * Creates new form FrameMantenimientoDueño
     */
    private int tipo;
    ConexionPostgres CP;
    DefaultTableModel modelo;

    public FrameMantenimientoDueño() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        tipo = 0;
        CP = new ConexionPostgres("dbProyecto", "usrUTN", "12345");
        correr();
        //llenar();
    }

    public void correr() {
        String principal[] = {"Cedula", "Nombre", "Apellido 1", "Apellido 2", "Telefono", "Direccion"};
        String datos[][] = {};
        modelo = new DefaultTableModel(datos, principal);
        tablaDueño.setModel(modelo);
        this.Select();
    }

    public void llenar() {
        cedula.setText((String) modelo.getValueAt(0, 0));
        nombre.setText((String) modelo.getValueAt(0, 1));
        apellido1.setText((String) modelo.getValueAt(0, 2));
        apellido2.setText((String) modelo.getValueAt(0, 3));
        telefono.setText((String) modelo.getValueAt(0, 4));
        direccion.setText((String) modelo.getValueAt(0, 5));
    }

    public void Select() {
        String ced = "";
        String nom = "";
        String ape1 = "";
        String ape2 = "";
        String tel = "";
        String dir = "";
        try {
            ResultSet datos = CP.select("*", "\"schProyecto\".\"dueno\"", "");
            while (datos.next()) {
                ced = datos.getString(1);
                nom = datos.getString(2);
                ape1 = datos.getString(3);
                ape2 = datos.getString(4);
                tel = datos.getString(5);
                dir = datos.getString(6);
                Object datostabla[] = {ced, nom, ape1, ape2, tel, dir};
                modelo.addRow(datostabla);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDueño = new javax.swing.JTable();
        cedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        insertar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDueño.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido 1", "Apellido 2", "Teléfono", "Dirección"
            }
        ));
        tablaDueño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDueñoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDueño);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 560, 150));

        cedula.setEditable(false);
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, -1));

        jLabel1.setText("Cédula");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        nombre.setEditable(false);
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, -1));

        jLabel3.setText("Apellido 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        apellido1.setEditable(false);
        getContentPane().add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 100, -1));

        jLabel4.setText("Apellido 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        apellido2.setEditable(false);
        getContentPane().add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 100, -1));

        jLabel5.setText("Teléfono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        telefono.setEditable(false);
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, -1));

        jLabel6.setText("Dirección");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        direccion.setEditable(false);
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 100, -1));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        insertar.setText("Insertar");
        insertar.setFocusable(false);
        insertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });
        jToolBar1.add(insertar);

        eliminar.setText("Eliminar");
        eliminar.setFocusable(false);
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(eliminar);

        modificar.setText("Modificar");
        modificar.setFocusable(false);
        modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jToolBar1.add(modificar);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        cedula.setText("");
        nombre.setText("");
        apellido1.setText("");
        apellido2.setText("");
        telefono.setText("");
        direccion.setText("");
        cedula.setEditable(true);
        nombre.setEditable(true);
        apellido1.setEditable(true);
        apellido2.setEditable(true);
        telefono.setEditable(true);
        direccion.setEditable(true);
        tipo = 1;
    }//GEN-LAST:event_insertarActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if (tipo == 1) {
            String datos = "";
            datos = "('" + this.cedula.getText() + "','"
                    + this.nombre.getText() + "','" + this.apellido1.getText() + "','"
                    + this.apellido2.getText() + "','" + this.telefono.getText() + "','" + this.direccion.getText() + "')";
            this.CP.insertar("\"schProyecto\".dueno", datos);
            cedula.setEditable(false);
            nombre.setEditable(false);
            apellido1.setEditable(false);
            apellido2.setEditable(false);
            telefono.setEditable(false);
            direccion.setEditable(false);
            correr();
        } else if (tipo == 2) {
            String estado;
            String datos;
            datos = "set \"nombre\" = '" + this.nombre.getText()
                    + "' where \"cedula\" = '" + this.cedula.getText() + "'";
            estado = this.CP.modificar("\"schProyecto\".dueno", datos);
            datos = "set \"apellido1\" = '" + this.apellido1.getText()
                    + "' where \"cedula\" = '" + this.cedula.getText() + "'";
            estado = this.CP.modificar("\"schProyecto\".dueno", datos);
            datos = "set \"apellido2\" = '" + this.apellido2.getText()
                    + "' where \"cedula\" = '" + this.cedula.getText() + "'";
            estado = this.CP.modificar("\"schProyecto\".dueno", datos);
            datos = "set \"telefono\" = '" + this.telefono.getText()
                    + "' where \"cedula\" = '" + this.cedula.getText() + "'";
            estado = this.CP.modificar("\"schProyecto\".dueno", datos);
            datos = "set \"direccion\" = '" + this.direccion.getText()
                    + "' where \"cedula\" = '" + this.cedula.getText() + "'";
            estado = this.CP.modificar("\"schProyecto\".dueno", datos);
            cedula.setEditable(false);
            nombre.setEditable(false);
            apellido1.setEditable(false);
            apellido2.setEditable(false);
            telefono.setEditable(false);
            direccion.setEditable(false);
            this.correr();
        } else if (tipo == 3) {
            String estado;
            String datos;
            datos = " where cedula = " + "'" + this.cedula.getText() + "'";
            estado = this.CP.borrar("\"schProyecto\".dueno", datos);
            correr();
            cedula.setText("");
            nombre.setText("");
            apellido1.setText("");
            apellido2.setText("");
            telefono.setText("");
            direccion.setText("");
        }
        tipo = 0;
    }//GEN-LAST:event_okActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        tipo = 3;
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        cedula.setEditable(true);
        nombre.setEditable(true);
        apellido1.setEditable(true);
        apellido2.setEditable(true);
        telefono.setEditable(true);
        direccion.setEditable(true);
        tipo = 2;
    }//GEN-LAST:event_modificarActionPerformed

    private void tablaDueñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDueñoMouseClicked
        cedula.setText((String) modelo.getValueAt(tablaDueño.getSelectedRow(), 0));
        nombre.setText((String) modelo.getValueAt(tablaDueño.getSelectedRow(), 1));
        apellido1.setText((String) modelo.getValueAt(tablaDueño.getSelectedRow(), 2));
        apellido2.setText((String) modelo.getValueAt(tablaDueño.getSelectedRow(), 3));
        telefono.setText((String) modelo.getValueAt(tablaDueño.getSelectedRow(), 4));
        direccion.setText((String) modelo.getValueAt(tablaDueño.getSelectedRow(), 5));
    }//GEN-LAST:event_tablaDueñoMouseClicked

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
        FramePrincipal frame = new FramePrincipal();
        frame.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMantenimientoDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMantenimientoDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMantenimientoDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMantenimientoDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameMantenimientoDueño().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrameMantenimientoDueño.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FrameMantenimientoDueño.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton ok;
    private javax.swing.JButton regresar;
    private javax.swing.JTable tablaDueño;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
