/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class FrameCrearCita extends javax.swing.JFrame {

    /**
     * Creates new form FrameMantenimientoDueño
     */
    private int tipo;
    ConexionPostgres CP;
    DefaultTableModel modelo;

    public FrameCrearCita() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        tipo = 0;
        CP = new ConexionPostgres("dbProyecto", "usrUTN", "12345");
        correr();
        comboMascota();
        comboAnno();
        //llenar();
    }

    public void comboAnno() {
        for (int i = 1900; i <= 2013; i++) {
            anno.addItem(i);
        }
    }

    public void comboMascota() throws SQLException {
        ResultSet datos = CP.select("cod_mascota", "\"schProyecto\".\"mascota\"", "");
        ResultSet datos2 = CP.select("nombre", "\"schProyecto\".\"mascota\"", "");
        String a = "";
        String b = "";
        while (datos.next()) {
            a = datos.getString(1);
            if (datos2.next()) {
                b = datos2.getString(1);
            }
            codMascota.addItem(a);
            nomMascota.addItem(b);
        }
    }

    public void correr() {
        String principal[] = {"Código Cita", "Código Mascota", "Fecha"};
        String datos[][] = {};
        modelo = new DefaultTableModel(datos, principal);
        tablaCita.setModel(modelo);
        this.Select();
    }

    public void llenar() {
        cod.setText((String) modelo.getValueAt(0, 0));
    }

    public void Select() {
        String codC = "";
        String fecha = "";
        String codM = "";
        try {
            ResultSet datos = CP.select("*", "\"schProyecto\".\"cita\"", "");
            while (datos.next()) {
                codC = datos.getString(1);
                codM = datos.getString(2);
                fecha = datos.getString(3);
                Object datostabla[] = {codC, codM, fecha};
                modelo.addRow(datostabla);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCita = new javax.swing.JTable();
        cod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        insertar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        nomMascota = new javax.swing.JComboBox();
        codMascota = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        mes = new javax.swing.JComboBox();
        dia = new javax.swing.JComboBox();
        anno = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido 1", "Apellido 2", "Teléfono", "Dirección"
            }
        ));
        tablaCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCita);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 560, 150));

        cod.setEditable(false);
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, -1));

        jLabel1.setText("Código de la Cita");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel2.setText("Código de la Mascota");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel3.setText("Fecha de la Cita");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        insertar.setText("Insertar");
        insertar.setFocusable(false);
        insertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });
        jToolBar1.add(insertar);

        eliminar.setText("Eliminar");
        eliminar.setFocusable(false);
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(eliminar);

        modificar.setText("Modificar");
        modificar.setFocusable(false);
        modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jToolBar1.add(modificar);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 30));

        nomMascota.setEnabled(false);
        nomMascota.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                nomMascotaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(nomMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, -1));

        codMascota.setEnabled(false);
        codMascota.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                codMascotaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(codMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 70, -1));

        jLabel7.setText("Nombre de La Mascota");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mes.setEnabled(false);
        mes.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                mesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dia.setEnabled(false);
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        anno.setEnabled(false);
        getContentPane().add(anno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        cod.setText("");
        codMascota.setEnabled(true);
        nomMascota.setEnabled(true);
        cod.setEditable(true);
        anno.setEnabled(true);
        mes.setEnabled(true);
        tipo = 1;
    }//GEN-LAST:event_insertarActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if (tipo == 1) {
            String datos = "";
            datos = "('" + this.cod.getText() + "','"
                    + this.codMascota.getSelectedItem().toString() + "','" + dia.getSelectedItem().toString() + "/" + (mes.getSelectedIndex() + 1) + "/" + anno.getSelectedItem().toString() + "')";
            this.CP.insertar("\"schProyecto\".cita", datos);
            cod.setEditable(false);
            codMascota.setEnabled(false);
            nomMascota.setEnabled(false);
            anno.setEnabled(false);
            mes.setEnabled(false);
            dia.setEnabled(false);
            correr();
        } else if (tipo == 2) {
            String estado;
            String datos;
            datos = "set \"cod_mascota\" = '" + this.codMascota.getSelectedItem().toString()
                    + "' where \"cod\" = '" + this.cod.getText() + "'";
            estado = this.CP.modificar("\"schProyecto\".cita", datos);
            datos = "set \"fecha_cita\" = '" + dia.getSelectedItem().toString() + "/" + (mes.getSelectedIndex() + 1) + "/" + anno.getSelectedItem().toString()
                    + "' where \"cod\" = '" + this.cod.getText() + "'";
            estado = this.CP.modificar("\"schProyecto\".cita", datos);
            cod.setEditable(false);
            codMascota.setEnabled(false);
            nomMascota.setEnabled(false);
            anno.setEnabled(false);
            mes.setEnabled(false);
            dia.setEnabled(false);
            this.correr();
        } else if (tipo == 3) {
            String estado;
            String datos;
            datos = " where cedula = " + "'" + this.cod.getText() + "'";
            estado = this.CP.borrar("\"schProyecto\".dueno", datos);
            correr();
            cod.setText("");
        }
        tipo = 0;
    }//GEN-LAST:event_okActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        tipo = 3;
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        cod.setEditable(true);
        codMascota.setEnabled(true);
        nomMascota.setEnabled(true);
        anno.setEnabled(true);
        mes.setEnabled(true);
        tipo = 2;
    }//GEN-LAST:event_modificarActionPerformed

    private void tablaCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCitaMouseClicked
        cod.setText((String) modelo.getValueAt(tablaCita.getSelectedRow(), 0));
        int ind = 0;
        for (int i = 0; i < codMascota.getItemCount(); i++) {
            codMascota.setSelectedIndex(i);
            String b = (String) modelo.getValueAt(tablaCita.getSelectedRow(), 3);
            if (b.equalsIgnoreCase(codMascota.getSelectedItem().toString())) {
                ind = i;
            }
        }
        codMascota.setSelectedIndex(ind);
        nomMascota.setSelectedIndex(ind);
    }//GEN-LAST:event_tablaCitaMouseClicked

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
        FramePrincipal frame = new FramePrincipal();
        frame.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    private void codMascotaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_codMascotaPopupMenuWillBecomeInvisible
        this.nomMascota.setSelectedIndex(codMascota.getSelectedIndex());
        this.nomMascota.repaint();
    }//GEN-LAST:event_codMascotaPopupMenuWillBecomeInvisible

    private void nomMascotaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_nomMascotaPopupMenuWillBecomeInvisible
        this.codMascota.setSelectedIndex(nomMascota.getSelectedIndex());
        this.codMascota.repaint();
    }//GEN-LAST:event_nomMascotaPopupMenuWillBecomeInvisible

    private void mesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_mesPopupMenuWillBecomeInvisible
        dia.removeAllItems();
        if (mes.getSelectedIndex() == 1) {
            for (int i = 1; i <= 28; i++) {
                dia.addItem(i);
            }
        } else if (mes.getSelectedIndex() == 0 || mes.getSelectedIndex() == 2 || mes.getSelectedIndex() == 4 || mes.getSelectedIndex() == 6 || mes.getSelectedIndex() == 7
                || mes.getSelectedIndex() == 9 || mes.getSelectedIndex() == 11) {
            for (int i = 1; i <= 31; i++) {
                dia.addItem(i);
            }
        } else {
            for (int i = 1; i <= 30; i++) {
                dia.addItem(i);
            }
        }
        dia.setEnabled(true);
    }//GEN-LAST:event_mesPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameCrearCita().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrameCrearCita.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FrameCrearCita.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anno;
    private javax.swing.JTextField cod;
    private javax.swing.JComboBox codMascota;
    private javax.swing.JComboBox dia;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox mes;
    private javax.swing.JButton modificar;
    private javax.swing.JComboBox nomMascota;
    private javax.swing.JButton ok;
    private javax.swing.JButton regresar;
    private javax.swing.JTable tablaCita;
    // End of variables declaration//GEN-END:variables
}
